preload = $HOME/projects/wallpaper/3d-tech.jpg
preload = $HOME/projects/wallpaper/ai-machine.png
wallpaper = eDP-1,$HOME/projects/wallpaper/3d-tech.jpg
wallpaper = eDP-2,$HOME/projects/wallpaper/ai-machine.png
splash = true
ipc = on
